apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
data:
  mapUsers: |
    - userarn: arn:aws:iam::811910214758:user/jbd-cli
      username: jbd-cli
      groups:
        - system:masters
    - userarn: arn:aws:iam::811910214758:user/simplebank-gh-ci
      username: simplebank-gh-ci
      groups:
        - system:masters
      
